name: Release v1

on:
  push:
    tags:
      - v1.*

jobs:
  deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: echo
        shell: bash
        run: |
          echo "Deploying ${{ github.ref_name	}} to dev"

  deploy-test:
    needs:
      - deploy-dev
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: echo
        shell: bash
        run: |
          echo "Deploying ${{ github.ref_name	}} to test"